Increase delay for sending page view
qdhayana/gatsby-plugin-matomo pull request #2
Opened 2021-07-26 09:56 UTC by SujayPrabhu96

# Issue:
https://app.asana.com/0/1181333741691281/1200438756262278

# Functionality changed
- Official plugin had simulated 2 `requestAnimationFrame` calls to send page view to matomo
- Now, it has been increased to 4

2021-07-29 15:14 UTC, jawakardurai requested changes

2021-07-29 15:14 UTC, jawakardurai commented on README.md
> +      logPageView: false,
They already have something like `trackLoad`.

```suggestion
      trackPageView: false,
```

2021-07-29 15:14 UTC, jawakardurai commented on README.md
> +      delayPageView: 64,
Do we still need this?

2021-07-29 17:07 UTC, SujayPrabhu96 commented on README.md
> +      logPageView: false,
No, [trackLoad](https://github.com/qdhayana/gatsby-plugin-matomo/pull/2/files#diff-2f15e01c012970971795674aff1caf0619691d7d47cfe1b5be49ac414bac09a2R56) is not for the page view.

Will update the naming while updating the directory structure

2021-08-05 14:16 UTC, jawakardurai requested changes

2021-08-05 14:16 UTC, jawakardurai commented on README.md
> +| `delayPageView`   | (optional) Delay for logging page view on matomo. Default is simulating 2 requestAnimationFrame calls i.e.`32`.
remove?

2021-08-05 14:16 UTC, jawakardurai commented on README.md
> +      delayPageView: 64,
?

2021-08-05 14:16 UTC, jawakardurai commented on gatsby-browser.js
> +    const { trackLoad = true, delayPageView = 32, logPageView = true } = pluginOptions
Remove delayPgeView related code?

2021-08-06 03:41 UTC, SujayPrabhu96 commented
Removed code related to `delayPgeView` and also have updated directory structure

2021-08-09 05:57 UTC, jawakardurai approved these changes

2021-08-09 05:57 UTC, merged